# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: آموزش برنامه نویسی به زبان جاوا
email: j2eedev.ir@gmail.com
description: آموزش زبان برنامه نویسی جاوا
baseurl: "" # the subpath of your site, e.g. /blog
highlighter: rouge
lang: "fa"
url: "http://j2eedev.ir" # the base hostname & protocol for your site
enforce_ssl: shawkyz.info
twitter_username: "j2eedev.ir"
facebook_username: "j2eedev.ir"
linkedin_username: "j2eedev.ir"
github_username:  "j2eedev.ir"
disqus_username:  "j2eedev.ir"

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

sass:
  sass_dir: assets/_sass
  style: compressed

images: '/assets/images'
